server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: thucvu.dev@gmail.com
    password: 310501Asd@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
